# Generated by Django 3.0 on 2020-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
